name: Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
    - uses: actions-rs/cargo@v1.0.1
    - name: Show version
      run: cargo -v
    - name: Run tests
      run: bash ./test.sh
